# src: ./shared/configs/lefthook.base.yml
# @(#) : lefthook 基本設定
#
# Copyright (c) 2025 atsushifx <http://github.com/atsushifx>
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

pre-commit:
  parallel: true
  commands:
    gitleaks:
      run: gitleaks protect --config ./configs/gitleaks.toml --staged

    secretlint:
      glob: "**/*"
      run: >
        secretlint
        --secretlintrc ./configs/secretlint.config.yaml
        --secretlintignore .gitignore
        --maskSecrets
        "{staged_files}"

    eslint:
      glob: "*.{js,ts,tsx}"
      run: pnpm lint -- {staged_files}

    eslint-types:
      glob: "*.{js,ts,tsx}"
      run: pnpm lint:types -- {staged_files}

    lint-spells:
      glob: "*.{js,ts,tsx}"
      run: pnpm lint:spells -- {staged_files}

commit-msg:
  parallel: true
  commands:
    commitlint:
      run: commitlint --config ./configs/commitlint.config.ts --edit
