# src: packages/@esta-utils/utils/configs/secretlint.config.yaml
# @(#) : secretlint configuration
#
# Copyright (c) 2025 atsushifx <https://github.com/atsushifx>
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

rules:
  - id: "@secretlint/secretlint-rule-preset-recommend"
