# src: ./configs/ls-lin.yaml
# @(#) : filename type linter
#
# Copyright (c) 2025 atsushifx <http://github.com/atsushifx>
#
# This software is released under the MIT License.
# https://opensource.org/licenses/MIT

ls:
  .dir: kebab-case | regex:^.[aa-z]+$
  .ts: kebab-case
  .types.ts: camelCase
  .class.ts: PascalCase

  scripts:
    .*: kebab-case
    common:
      .*: kebab-case | PascalCase
    libs:
      .*: PascalCase
    tests:
      .*: PascalCase

  packages:
    .dir: kebab-case | regex:^@[a-z\-]+$ | regex:__tests__
    .ts: camelCase | PascalCase
    .type.ts: camelCase
    .class.ts: PascalCase

# ignore directories
ignore:
  - "**/.git"
  - "**/.github"
  - "**/lib"
  - "**/module"
  - "**/node_modules"
  - "**/.textlint"
  - "**/.cache"
  - "**/.vscode"
